### ISSUE TITLE
Modernize and improve web UI for Zeroconf-Lookup browser extension

### ISSUE THREAD

**Issue by anklimov** [anklimov/zeroconf-lighthub#1]
Propose a comprehensive UI/UX update for the Zeroconf-Lookup browser extension popup (Chrome/Firefox). Goals:

- Modernize the appearance (fonts, colors, shadows, rounded corners)
- Use device cards instead of plain rows for discovered devices
- Add device icons and actionable buttons with tooltips
- Enhance spinner/loader visuals
- Add search/filter bar for devices
- Improve accessibility (contrast, ARIA labels, keyboard navigation)
- Add dark mode support

Example CSS changes:
```css
html, body {
  font-family: 'Segoe UI', Arial, sans-serif;
  background: #f5f7fa;
  color: #222;
  min-width: 22em;
  margin: 0;
  padding: 0;
}

.container {
  padding: 1em;
}

.device-card {
  background: #fff;
  border-radius: 8px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.07);
  margin-bottom: 12px;
  padding: 1em;
  display: flex;
  align-items: center;
  justify-content: space-between;
  transition: box-shadow 0.2s;
}
.device-card:hover {
  box-shadow: 0 2px 8px rgba(44,62,80,0.13);
}

.device-info {
  display: flex;
  align-items: center;
}

.device-icon {
  width: 32px;
  height: 32px;
  margin-right: 1em;
}

.device-name {
  font-weight: 600;
}

.button {
  border: none;
  background: #27ae60;
  color: #fff;
  padding: 0.5em 1.2em;
  border-radius: 4px;
  cursor: pointer;
  font-weight: 600;
  transition: background 0.2s;
}
.button:hover {
  background: #219150;
}

#spinner {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 1em 0;
}
.spinner-dot {
  width: 8px;
  height: 8px;
  margin: 0 2px;
  background: #27ae60;
  border-radius: 50%;
  animation: bounce 1.2s infinite ease-in-out both;
}
.spinner-dot:nth-child(2) { animation-delay: -0.32s; }
.spinner-dot:nth-child(3) { animation-delay: -0.16s; }
@keyframes bounce {
  0%, 80%, 100% { transform: scale(0.8); }
  40% { transform: scale(1.4); }
}
```

Example HTML structure for popup:
```html
<div class="container">
  <h3>Discovered Devices</h3>
  <div id="devices-list">
    <div class="device-card">
      <div class="device-info">
        <img src="icons/device.svg" class="device-icon" alt="Device">
        <span class="device-name">Railduino</span>
      </div>
      <button class="button">Edit</button>
    </div>
  </div>
  <div id="spinner" style="display:none;">
    <div class="spinner-dot"></div>
    <div class="spinner-dot"></div>
    <div class="spinner-dot"></div>
  </div>
</div>
```

See also popup JS updates and further accessibility improvements. Would involve updating `Chrome/popup/lookup.css`, `lookup.html`, and related files.
